name: OnewithSaraJ
favicon: null
layout_spectrum: 0.61187
typography_spectrum: 0.45312
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020001'
    - '#fffee9'
    - '#ab9b81'
    - '#73616d'
    - '#d9ccc6'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0
  rhythmicContrast: 0
purpose: []
