name: OnewithSaraJ
favicon: null
layout_spectrum: 0.7047306431923062
typography_spectrum: 0.38481429289095104
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8da4d6'
    - '#262b3f'
    - '#f3e2d0'
    - '#495969'
    - '#ce8f23'
  brandStrength: 0.3125
  lightness: 0.4160564932972193
  saturation: 0.4064350661356002
  rhythmicContrast: 1
purpose: []
