layout_spectrum: 0.07513353228569031
typography_spectrum: 0.4558425615541637
color:
  brandColors:
    - '#31090A'
    - '#E3A5F3'
    - '#D26606'
    - '#FD3C33'
    - '#F59B08'
  brandStrength: 0.8350633778609335
  lightness: 0.12180482712574303
  saturation: 0.2053884246852249
  rhythmicContrast: 0.09442955977283418
name: OnewithSaraJ
favicon: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
